### ISSUE TITLE
about conv after bert feature

### ISSUE THREAD

**Issue by hsjkdjj** [maszhongming/Effective_Extractive_Summarization#6]
hi there, i find you add 3 conv layers to encode the article after bert feature extraction and I didn't find any clue in the paper, plus, i think in the  code conv is applied to each subsentence, could you tell me the reason and what's the problem if i take the whole article as a sent to just get bert output?

**Comment by maszhongming** [comment]
Here CNN is a sentence encoder, as we described in section 3.2.1. It is worth noting that BERT (feature-based) in this paper is used to provide word embedding, so we keep the remaining structure unchanged (including sentence encoder CNN). You can take the whole article as a sentence to get BERT output, but you still need some structures to help you get the representation of each sentence (such as mean pooling, CNN).
