### ISSUE TITLE
Code not running on Colab

### ISSUE THREAD

**Issue by kchax4377** [maszhongming/Effective_Extractive_Summarization#7]
I tried to execute the command on Google Colab :

!CUDA_VISIBLE_DEVICES=0 python ./main.py --mode=train --encoder=BiLSTM --decoder=PN --emb_type=W2V

but got the following errors:

Model name '/uncased_L-24_H-1024_A-16/vocab.txt' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese). We assumed '/uncased_L-24_H-1024_A-16/vocab.txt' was a path or url but couldn't find any file associated to this path or url.
Traceback (most recent call last):
  File "./main.py", line 344, in <module>
    train(args)
  File "./main.py", line 159, in train
    word2id, args.cuda, args.debug)
  File "./main.py", line 102, in build_batchers
    ExtractDataset('val'), batch_size=BUCKET_SIZE,
  File "./main.py", line 47, in __init__
    super().__init__(split, DATA_DIR)
  File "/content/drive/My Drive/Effective_Extractive_Summarization-master/data/data.py", line 14, in __init__
    self._n_data = _count_data(self._data_path)
  File "/content/drive/My Drive/Effective_Extractive_Summarization-master/data/data.py", line 29, in _count_data
    names = os.listdir(path)
OSError: [Errno 5] Input/output error: '/content/drive/My Drive/Effective_Extractive_Summarization-master/CNNDM/val'

I have downloaded the bert-large-uncased model from https://storage.googleapis.com/bert_models/2018_10_18/uncased_L-24_H-1024_A-16.zip

**Comment by maszhongming** [comment]
It may seem to be a problem with Colab, you can refer to issue like [this](https://github.com/googlecolab/colabtools/issues/510).

**Comment by kchax4377** [comment]
Okay understood. Its a problem with Colab's usage restrictions. But anyway, @maszhongming  then could you please share the pretrained models as I don't want to train on my data. I just want to test my data on the pretrained models.

**Comment by maszhongming** [comment]
Sorry, we don't have all the pre-trained models now. If you want to use a pre-trained model, maybe you can refer to our recent work [here](https://github.com/maszhongming/MatchSum).
