### ISSUE TITLE
Need source code for processing CNN/DM dataset

### ISSUE THREAD

**Issue by MTATrooper** [maszhongming/Effective_Extractive_Summarization#8]
Can you release source code for process CNN/DM dataset?

**Comment by maszhongming** [comment]
We used the preprocessing code [here](https://github.com/ChenRocks/cnn-dailymail).

**Comment by MTATrooper** [comment]
> We used the preprocessing code [here](https://github.com/ChenRocks/cnn-dailymail).
Thank you! Can you explain more clearly about creating extractive labels?

**Comment by MTATrooper** [comment]
Thank you! Can you explain more clearly about creating extractive labels?

**Comment by maszhongming** [comment]
You can refer to [issue3](https://github.com/maszhongming/Effective_Extractive_Summarization/issues/3).
